### ISSUE TITLE
Posibility to fetch data based on given stock code and date range

### ISSUE THREAD

**Issue by edgedalmacio** [phisix-org/phisix#1]
_From [biboyati...@gmail.com](https://code.google.com/u/110192093149258446799/) on July 03, 2013 11:01:57_

Please provide any additional information below. - Please extend the current API, say will return data based on a given stock Code and a From and To date range.

Thanks!

_Original issue: http://code.google.com/p/phisix/issues/detail?id=1_

**Comment by rajeem** [comment]
It looks like this feature doesn't work anymore?
