### ISSUE TITLE
API cannot be reached

### ISSUE THREAD

**Issue by 32x0lf** [phisix-org/phisix#153]
Is there any changes on the api or url? I can no longer access the api. Thank you

**Comment by maclaine-san** [comment]
same here. Tried using http://phisix-api.appspot.com/stocks.{json|xml}. Is this a dead project?

**Comment by edgedalmacio** [comment]
> Is there any changes on the api or url? I can no longer access the api. Thank you

@32x0lf  You can get uptime stats here: https://statuspage.freshping.io/29889-phisixapi

> same here. Tried using [http://phisix-api.appspot.com/stocks.{json|xml}](http://phisix-api.appspot.com/stocks.%7Bjson%7Cxml%7D). Is this a dead project?

@maclaine-san you can change the API response payload by choosing either `json` or `XML`.

Example: 

- JSON payload: http://phisix-api.appspot.com/stocks.json
- XML payload: http://phisix-api.appspot.com/stocks.xml

**Comment by maclaine-san** [comment]
@edgedalmacio yes just to be clear I tried each xml and json formats yesterday :). Guess it's working now. Thanks!

**Comment by 32x0lf** [comment]
Can you please show me what did you do to make it work on your side?. I tried everything from json to xml and api to api4 but none of them seems to work on my side. but this works
previously with me around 2020.

**Comment by maclaine-san** [comment]
All their GET endpoints are working for me, so I'm not sure what you mean
here, but you can submit a new issue with detailed steps to replicate your
issue.

**Comment by 32x0lf** [comment]
I figured it out. I changed my DNS from dynamic to public google dns
8.8.8.8 and I got results. Thanks
