### ISSUE TITLE
empty prices

### ISSUE THREAD

**Issue by errolflynn09** [phisix-org/phisix#185]
I'm not getting any price when I access the pages. It's just blank. Looks like something is wrong.

**Comment by errolflynn09** [comment]
I think this also happened yesterday.

**Comment by ianquia** [comment]
![image](https://user-images.githubusercontent.com/4545122/129675616-ea9dbf90-7b2e-4051-9812-7029d5b74549.png)
http://phisix-api3.appspot.com/stocks.json
http://phisix-api3.appspot.com/stocks/BDO.json

I'm getting a 500 error on the page.

**Comment by ianquia** [comment]
Its up now :) thanks
