### ISSUE TITLE
Date parameter does not work

### ISSUE THREAD

**Issue by joeypencil** [phisix-org/phisix#334]
I have already tried the following URLs but none of them work:
- http://phisix-api.appspot.com/stocks/LTG.2023-07-20.json
- http://phisix-api.appspot.com/stocks/LTG.2023-7-20.json
- http://phisix-api.appspot.com/stocks/LTG.2023-July-20.json
- http://phisix-api.appspot.com/stocks/LTG.2023-july-20.json

**Comment by glide143** [comment]
I believe this might be related to the recent modifications in #331 
Let's patiently wait for it to be resolved. However, if you require access to the previous data, I have archived them for reference.
https://res.cloudinary.com/dg4jbnenh/raw/upload/v1690361209/data/data-2023-07-20.json

**Comment by briancalma** [comment]
Just to update the mentioned route endpoints above are still not working, here are also my test route endpoints:
http://phisix-api.appspot.com/stocks/BDO.2023-09-10.json
http://phisix-api.appspot.com/stocks/BDO.2023-9-10.json
http://phisix-api.appspot.com/stocks/BDO.2023-September-10.json
http://phisix-api.appspot.com/stocks/BDO.2023-september-10.json
http://phisix-api.appspot.com/stocks/BDO.2023-Sept-10.json
http://phisix-api.appspot.com/stocks/BDO.2023-sept-10.json
